config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'posts#index'
  resources :posts do
    member do 
      post '/create_comment' => 'posts#create_comment', as: 'create_comment_to'
      post '/like_post' => 'posts#like_post', as: 'like_to'
    end
    collection do 
      delete '/:cmtid/delete_comment' => 'posts#delete_comment', as: 'delete_comment_to' 
    end
  end
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    has_many :likes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :likes       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :create_comment, :like_post]
  before_action :is_login?, only: [:create_commnet, :like_post, :destory_comment]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @like = true
    if user_signed_in?
      @like = current_user.likes.find_by(post_id: @post.id).nil?
    end 
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def create_comment
    # ajax 로 동작하는 코드
    # 자동으로 js 파일을 먼저 찾고 erb 파일을 찾음 
    # create_commnet.js.erb  

    @c = @post.comments.create(comment_params)
    
  end

  def delete_comment
    # ajax 로 동작하는 코드
    # 자동으로 js 파일을 먼저 찾고 erb 파일을 찾음 
    # create_commnet.js.erb  

    puts params[:cmtid]
    @c = Comment.find(params[:cmtid]).destroy
  end

  def like_post
    
    #현재 post와 user 가 누룬 like 다 가져오기  
    #Like.where 여러 줄을 return 함
    if Like.where(user_id: current_user.id, post_id: @post.id).first.nil?
      #좋아요를 누루지 않음 
      @result = current_user.likes.create(post_id: @post.id)
      # puts"좋아요"
    else
      #좋아요를 누름 
      @result = current_user.likes.find_by(post_id: @post.id).destroy
      # puts"안좋아요"
    end 
    
    # 메모리에만 있고 DB 에는 있지 않은 상태 freeze
    @result = @result.frozen?

  end

  private
    def is_login?
      unless user_signed_in?
      # ajax 는 페이지 전환을 할 수 없다. js 에서 해야함 redirect_to 가 불가능 함
      # respond_to method 를 통해 다른 format 으로 전달함 
        respond_to do |format|
          format.js {render 'please_login.js.erb'}
        end
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content)
    end
    
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%=link_to "SIGN OUT", destroy_user_session_path, method: :delete, class:"btn btn-danger", data:{confirm: "로그아웃 하시겟습니까"} %>
<% else %>
  <%=link_to "SIGN IN", new_user_session_path, class:"btn btn-info"%>
<% end %>

<%=link_to "HOME", root_path , class:"btn btn-success"%>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title , class:'form-control' %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, class:'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit "작성", class:'btn btn-success' %>
  </div>
<% end %>

<script src="/form-control.js"></script>

app/views/posts/create_comment.js.erb
alert("댓글이 등록됨");
$('#comment_body').val("");
$('#comment_table tbody').prepend('<tr id="<%= "comment-#{@c.id}" %>"><td><%= @c.body %></td><td><%= link_to "삭제", delete_comment_to_posts_path(@c.id), method: :delete, class: 'btn btn-warning delete_comment', id: @c.id, data: {confirm: "삭제하시겠습니까?"}, remote: true %></td></tr>');

app/views/posts/delete_comment.js.erb
$('#comment-<%= @c.id %>').fadeOut();

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table id='mytable' class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td class=title><%= post.title %></td>
        <td class=content><%= post.content %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

  <h3>javascript test</h3>

<button id='setTitle'>setTitle</button>
<button id='setClass'>setClass</button>
<button id='setAttribute'>setAttribute</button>

<script src="./come.js"></script>
<script src="./title.js"></script>
<script src="./class.js"></script>
<script src="./attribute.js"></script>

app/views/posts/like_post.js.erb
if(<%=@result%>){
    $('#like_button').text("Like").addClass("btn-info").removeClass("btn-danger");
}else {
    $('#like_button').text("Disike").addClass("btn-danger").removeClass("btn-info");
}
                  
$('#like_count').text(<%=@post.likes.count%>)

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/please_login.js.erb
if(confirm("로그인이 필요합니다.\n 로그인 페이지로 이동하시겠습니까?"))
{
    location.href = "<%=new_user_session_path %>";
}

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>


<%= form_tag create_comment_to_post_path, id: "comment" do %>
  <%= text_field_tag "comment[body]" %>
  <%= submit_tag "댓글달기"%>
<% end %>

<%= link_to 'Edit', edit_post_path(@post), class:'btn btn-warning' %> 
<%= link_to 'Back', posts_path, class:'btn btn-success'%>
<% if @like %>
  <%= link_to "Like", like_to_post_path, class:'btn btn-info', id:"like_button" %>
<% else %>
  <%= link_to "Dislike", like_to_post_path, class:'btn btn-danger', id:"like_button" %>
<% end %>
<span id='like_count'><%=@post.likes.count %></span>

<table class='table' id="comment_table">
  <thead>
    <tr>
      <th>댓글</th>
    </tr>
  </thead>
  <tbody>
    <% @post.comments.reverse.each do |p|%>
    <tr id="comment-<%= p.id %>">
      <td><%= p.body %></td>
      <td><%= link_to "삭제", delete_comment_to_posts_path(p.id), method: :delete, data: {confirm: "삭제하시겠습니까?"}, class: "btn btn-danger", remote: true %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<script>
  $(function() {
    var form = $('#comment');
    form.on('submit', function(e){
      //화면전환을 하지 않음 
      e.preventDefault();
      //현재 입력되어 있는 값을 가져옴 
      //var contents = $("comment_body").val();
      var contents = form.serialize(); //한꺼번에 input tag 전부 넘기기 
      console.log(contents);
      $.ajax({
        //어디로 무엇이 갈지 설정 
        url: "<%=create_comment_to_post_path %>",
        method: "POST",
        data: contents
      });
    });
    
    
    $('#like_button').on('click', function(e){
      e.preventDefault();
      console.log("Like btn clikced");
      $.ajax({
        method: "POST",
        url:"<%=like_to_post_path %>"
      });
    });
    
    // $(document).on('click', '#like_button', function(){
        
    // })
    
    // var delbtn = $('#del_comment');
    // delbtn.on('click', function(e){
    //   //화면전환을 하지 않음 
    //   e.preventDefault();
    //   var cmtid = $(this).attr('id');
    //   //현재 입력되어 있는 값을 가져옴 
    //   var contents = $('#body').val();
    //   console.log(contents);
    //   $.ajax({
    //     //어디로 무엇이 갈지 설정 
    //     url: "<--%=delete_comment_to_post_path %>",
    //     method: "delete",
    //     data: {body: contents}
    //   });
    // });
  });
  
</script>